<?php

return [
    [
        'name' => 'typeBoleta',
        'valueText' => 'Semanal',
        'valueNumber' => 1,
        'module' => 'boleta',
        'description' => 'Tipo de Boleta Semanal',
    ],
    [
        'name' => 'typeBoleta',
        'valueText' => 'Mensual',
        'valueNumber' => 2,
        'module' => 'boleta',
        'description' => 'Tipo de Boleta Semanal',
    ],
    [
        'name' => 'daysOfWeek',
        'valueText' => null,
        'valueNumber' => 7,
        'module' => null,
        'description' => 'Dias de una semana',
    ],
    [
        'name' => 'empresa',
        'valueText' => 'SERMEIND FABRICACIONES INDUSTRIALES S.A.C.',
        'valueNumber' => 0,
        'module' => 'boleta',
        'description' => 'Nombre la empresa sermeind',
    ],
    [
        'name' => 'ruc',
        'valueText' => '20540001384',
        'valueNumber' => 0,
        'module' => 'boleta',
        'description' => 'Ruc la empresa sermeind',
    ],
    [
        'name' => 'horasXDia',
        'valueText' => null,
        'valueNumber' => 8,
        'module' => 'boleta',
        'description' => 'Horas trabajadas por día',
    ],
    [
        'name' => 'diasMes',
        'valueText' => null,
        'valueNumber' => 30,
        'module' => 'boleta',
        'description' => 'Dias por mes',
    ],
    [
        'name' => 'horasSemanales',
        'valueText' => null,
        'valueNumber' => 48,
        'module' => 'boleta',
        'description' => 'Horas máximas por semana',
    ],
    [
        'name' => 'tipoDomumento',
        'valueText' => 'DNI',
        'valueNumber' => 1,
        'module' => 'boleta',
        'description' => 'Tipo de documento DNI',
    ],
    [
        'name' => 'tipoDomumento',
        'valueText' => 'RUC',
        'valueNumber' => 2,
        'module' => 'boleta',
        'description' => 'Tipo de documento RUC',
    ],
    [
        'name' => 'tipoDomumento',
        'valueText' => 'C.E.',
        'valueNumber' => 3,
        'module' => 'boleta',
        'description' => 'Tipo de documento C.E.',
    ],
    [
        'name' => 'daysToExpireMin',
        'valueText' => null,
        'valueNumber' => 8,
        'module' => 'credit',
        'description' => 'Dias minimos para cambiar a Expire',
    ],
    [
        'name' => 'start_rotation_baja',
        'valueText' => 's_r_b',
        'valueNumber' => 0,
        'module' => 'material',
        'description' => 'Inicio porcentage rotacion baja',
    ],
    [
        'name' => 'end_rotation_baja',
        'valueText' => 'e_r_b',
        'valueNumber' => 40,
        'module' => 'material',
        'description' => 'Fin porcentage rotacion baja',
    ],
    [
        'name' => 'start_rotation_media',
        'valueText' => 's_r_m',
        'valueNumber' => 40,
        'module' => 'material',
        'description' => 'Inicio porcentage rotacion media',
    ],
    [
        'name' => 'end_rotation_media',
        'valueText' => 'e_r_m',
        'valueNumber' => 70,
        'module' => 'material',
        'description' => 'Fin porcentage rotacion media',
    ],
    [
        'name' => 'start_rotation_alta',
        'valueText' => 's_r_a',
        'valueNumber' => 70,
        'module' => 'material',
        'description' => 'Inicio porcentage rotacion alta',
    ],
    [
        'name' => 'type_current',
        'valueText' => 'pen',
        'valueNumber' => 0,
        'module' => 'general',
        'description' => 'Tipo de moneda',
    ],
    [
        'name' => 'address',
        'valueText' => 'AV. EL POLO 670, SANTIAGO DE SURCO, LIMA',
        'valueNumber' => null,
        'module' => null,
        'description' => 'Direccion de la tienda',
    ],
    [
        'name' => 'idWarehouseTienda',
        'valueText' => null,
        'valueNumber' => 5,
        'module' => null,
        'description' => 'Id del almacen de tienda',
    ],
    [
        'name' => 'store_material_min',
        'valueText' => null,
        'valueNumber' => 120,
        'module' => null,
        'description' => 'Cantidad minima de productos en tienda',
    ],
    [
        'name' => 'typeFactura',
        'valueText' => null,
        'valueNumber' => null,
        'module' => null,
        'description' => null,
    ],
    [
        'name' => 'send_notification_store_pop_up',
        'valueText' => 's',
        'valueNumber' => null,
        'module' => null,
        'description' => 'Envio de notificacion de tienda via pop up',
    ],
    [
        'name' => 'send_notification_store_campana',
        'valueText' => 's',
        'valueNumber' => null,
        'module' => null,
        'description' => 'Envio de notificaciones via campana',
    ],
    [
        'name' => 'send_notification_store_email',
        'valueText' => null,
        'valueNumber' => null,
        'module' => null,
        'description' => null,
    ],
    [
        'name' => 'send_notification_store_telegram',
        'valueText' => null,
        'valueNumber' => null,
        'module' => null,
        'description' => null,
    ],
    [
        'name' => 'tipo_meta',
        'valueText' => 'semanal',
        'valueNumber' => null,
        'module' => null,
        'description' => null,
    ],
    [
        'name' => 'punto_venta_worker',
        'valueText' => 'si',
        'valueNumber' => 0,
        'module' => null,
        'description' => null,
    ],
];
